[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# we need to tell Foundry that @chainlink/contracts should point to lib folder
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts"]
# ffi = true, allow Foundry to run commands directly on machine
ffi = true
fs_permissions = [{ access = "read", path = "./broadcast" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
